version: '3.8'
services:
  atscale-gatling:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./config/systems.properties:/app/systems.properties:ro
    container_name: atscale-gatling-runner
